import cv2
import numpy as np
import math
from enum import Enum
from matplotlib import image as mpimage
from matplotlib import pyplot as plt
import glob
import csv

class OrangeHSVSeg:
    """
    An OpenCV pipeline generated by GRIP.
    """
    
    def __init__(self):
        """initializes all values to presets or None if need to be set
        """

        self.__hsv_threshold_hue = [0, 30]
        self.__hsv_threshold_saturation = [102, 192]
        self.__hsv_threshold_value = [190, 255]

        self.hsv_threshold_output = None


    def process(self, source0):
        """
        Runs the pipeline and sets all outputs to new values.
        """
        # Step HSV_Threshold0:
        self.__hsv_threshold_input = source0
        (self.hsv_threshold_output) = self.__hsv_threshold(self.__hsv_threshold_input, self.__hsv_threshold_hue, self.__hsv_threshold_saturation, self.__hsv_threshold_value)


    @staticmethod
    def __hsv_threshold(input, hue, sat, val):
        """Segment an image based on hue, saturation, and value ranges.
        Args:
            input: A BGR numpy.ndarray.
            hue: A list of two numbers the are the min and max hue.
            sat: A list of two numbers the are the min and max saturation.
            lum: A list of two numbers the are the min and max value.
        Returns:
            A black and white numpy.ndarray.
        """
        out = cv2.cvtColor(input, cv2.COLOR_RGB2HSV)
        return cv2.inRange(out, (hue[0], sat[0], val[0]),  (hue[1], sat[1], val[1]))


def ROC(lab, genLab, thresh):

    for i in range(len(thresh)):
        for f, val in lab.items():

            if val == genLab[f]:
                print('true')
            else:
                print('false')

# End ROC

def isOrange(segIm, thresh):

    count = np.count_nonzero(segIm)

    if count >= thresh:
        print('orange')
        return True
    else:
        print('false')
        return False
    # End if

# End isOrange


threshold = np.arange(0, 10001, 10)

# Read in the labels for images
reader = csv.reader(open('localData/labels.csv'))

labels = {}
genLabels = {}

for row in reader:

    key = row[0]

    if row[1] == 'people':
        labels[key] = True
    else:
        labels[key] = False
    # End if


# End for

# Create system pipeline.
segPipe = OrangeHSVSeg()

# Read images one at a time and put them through color segmentation.
for fName in glob.glob('localData/images/*.jpg'):

    genLabels[fName] = []

    image = mpimage.imread(fName)

    # Segment image
    segPipe.process(image)
    segImage = segPipe.hsv_threshold_output
    
    # For each image, cycle through thresholds.
    for i in threshold:

        # Determine label based on threshold
        genLabels[fName].append(isOrange(segImage, i))

    # End for

# End for

ROC(labels, genLabels, threshold)

# End isOrange


#testyDo = mpimage.imread('localData/images/AMountain_0001-00491.jpg')

#thingy = OrangeHSVSeg()

#thingy.process(testyDo)

#segyBoi = thingy.hsv_threshold_output

#plt.imshow(segyBoi, cmap='gray')

#plt.show()
